### ISSUE TITLE
about the test

### ISSUE THREAD

**Issue by Duanener** [qingshi9974/ICLR2024-FTIC#4]
What a wonderful work! However, I encounter  some issues while running the eval.py.

When I use following command:
`python eval.py --data ./kodak --checkpoint ./ckpt_0483.pth  --cuda --real`
I get following erro:
```
Loading ./ckpt_0483.pth
Traceback (most recent call last):
  File "/home/xxduan/FTIC/eval.py", line 169, in <module>
    main(sys.argv[1:])
  File "/home/xxduan/FTIC/eval.py", line 117, in main
    out_enc = net.compress(x_padded)
  File "/home/xxduan/FTIC/models/flic.py", line 505, in compress
    pmf = self._likelihood(samples, scale[0][c_idx][h_idx][w_idx],means=mu[0][c_idx][h_idx][w_idx]+minmax)
  File "/home/xxduan/FTIC/models/flic.py", line 528, in _likelihood
    scales = lower_bound(scales)
  File "/home/xxduan/.conda/envs/TCM/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xxduan/.conda/envs/TCM/lib/python3.9/site-packages/compressai/ops/bound_ops.py", line 80, in forward
    return self.lower_bound(x)
  File "/home/xxduan/.conda/envs/TCM/lib/python3.9/site-packages/compressai/ops/bound_ops.py", line 75, in lower_bound
    return LowerBoundFunction.apply(x, self.bound)
  File "/home/xxduan/.conda/envs/TCM/lib/python3.9/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/xxduan/.conda/envs/TCM/lib/python3.9/site-packages/compressai/ops/bound_ops.py", line 51, in forward
    return lower_bound_fwd(x, bound)
  File "/home/xxduan/.conda/envs/TCM/lib/python3.9/site-packages/compressai/ops/bound_ops.py", line 37, in lower_bound_fwd
    return torch.max(x, bound)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```
If I remove the --cuda from the command line, the program runs correctly, but slowly.
Please how can I modify it so that it can run compress and decompress functions on the gpu.

**Comment by qingshi9974** [comment]
> What a wonderful work! However, I encounter some issues while running the eval.py.
> 
> When I use following command: `python eval.py --data ./kodak --checkpoint ./ckpt_0483.pth --cuda --real` I get following erro:
> 
> ```
> Loading ./ckpt_0483.pth
> Traceback (most recent call last):
>   File "/home/xxduan/FTIC/eval.py", line 169, in <module>
>     main(sys.argv[1:])
>   File "/home/xxduan/FTIC/eval.py", line 117, in main
>     out_enc = net.compress(x_padded)
>   File "/home/xxduan/FTIC/models/flic.py", line 505, in compress
>     pmf = self._likelihood(samples, scale[0][c_idx][h_idx][w_idx],means=mu[0][c_idx][h_idx][w_idx]+minmax)
>   File "/home/xxduan/FTIC/models/flic.py", line 528, in _likelihood
>     scales = lower_bound(scales)
>   File "/home/xxduan/.conda/envs/TCM/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/xxduan/.conda/envs/TCM/lib/python3.9/site-packages/compressai/ops/bound_ops.py", line 80, in forward
>     return self.lower_bound(x)
>   File "/home/xxduan/.conda/envs/TCM/lib/python3.9/site-packages/compressai/ops/bound_ops.py", line 75, in lower_bound
>     return LowerBoundFunction.apply(x, self.bound)
>   File "/home/xxduan/.conda/envs/TCM/lib/python3.9/site-packages/torch/autograd/function.py", line 506, in apply
>     return super().apply(*args, **kwargs)  # type: ignore[misc]
>   File "/home/xxduan/.conda/envs/TCM/lib/python3.9/site-packages/compressai/ops/bound_ops.py", line 51, in forward
>     return lower_bound_fwd(x, bound)
>   File "/home/xxduan/.conda/envs/TCM/lib/python3.9/site-packages/compressai/ops/bound_ops.py", line 37, in lower_bound_fwd
>     return torch.max(x, bound)
> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
> ```
> 
> If I remove the --cuda from the command line, the program runs correctly, but slowly. Please how can I modify it so that it can run compress and decompress functions on the gpu.

Thanks for the reminder, i've fixed the problem.  The test code can now run correctly with _--cuda_ .

In addition, we use the one-pass range coder of the [cheng2020] (https://github.com/ZhengxueCheng/Learned-Image-Compression-with-GMM-and-Attention/blob/master/network.py), which is slower than the two-pass range coder of _compressai._

You can also implement the test code by removing --real, the results are almost the  same with the real encoding and decoding process.

**Comment by Duanener** [comment]
Thank you for your kind reply. However, I wonder why we couldn't use two-pass range coder of compressai. Couldn't we use [GaussianConditional](https://github.com/InterDigitalInc/CompressAI/blob/master/compressai/entropy_models/entropy_models.py#L582) to estimate the bpp of y_hat = Q(y), as I know the default  y_hat= Q(y-mu) + mu.

**Comment by qingshi9974** [comment]
Most of the entropy models in compressai usually center the representation with the mean prediction during quantization, thus encoding Q(y-mu).  In this way, the Gaussian probability distribution is shifted to zero, so we can use the "scale table" to look up the cumulative probability a directly and implement Ranger coding quickly.
﻿
However, in our autoregressive entropy models, this poses a problem because during training we do not know the mean before a pass through the model, so we would have to multiply the forward passes to get it.  To simplify the setup, we follow [1,2] to simply drop this and encode Q(y) directly. So we don't use the range coder of compressai. In the future, we will try to modify the entropy coding process to make it faster.

[1] Xiang, Jinxi, Kuan Tian, and Jun Zhang. "Mimt: Masked image modeling transformer for video compression." The Eleventh International Conference on Learning Representations. 2023.
[2] Mentzer, Fabian, et al. "VCT: A Video Compression Transformer." Advances in Neural Information Processing Systems 35 (2022): 13091-13103.
[3] Mentzer, Fabian, Eirikur Agustson, and Michael Tschannen. "M2t: Masking transformers twice for faster decoding." Proceedings of the IEEE/CVF International Conference on Computer Vision. 2023.

**Comment by qingshi9974** [comment]
> Thank you for your kind reply. However, I wonder why we couldn't use two-pass range coder of compressai. Couldn't we use [GaussianConditional](https://github.com/InterDigitalInc/CompressAI/blob/master/compressai/entropy_models/entropy_models.py#L582) to estimate the bpp of y_hat = Q(y), as I know the default y_hat= Q(y-mu) + mu.

Most of the entropy models in compressai usually center the representation with the mean prediction during quantization, thus encoding Q(y-mu).  In this way, the Gaussian probability distribution is shifted to zero, so we can use the "scale table" to look up the cumulative probability a directly and implement Ranger coding quickly.
﻿
However, in our autoregressive entropy models, this poses a problem because during training we do not know the mean before a pass through the model, so we would have to multiply the forward passes to get it.  To simplify the setup, we follow [1,2,3] to drop this and encode Q(y) directly. So we don't use the range coder of compressai. In the future, we will try to modify the entropy coding process to make it faster.
[1] Xiang, Jinxi, Kuan Tian, and Jun Zhang. "Mimt: Masked image modeling transformer for video compression." The Eleventh International Conference on Learning Representations. 2023.
[2] Mentzer, Fabian, et al. "VCT: A Video Compression Transformer." Advances in Neural Information Processing Systems. 2022.
[3]Mentzer, Fabian, Eirikur Agustson, and Michael Tschannen. "M2t: Masking transformers twice for faster decoding." Proceedings of the IEEE/CVF International Conference on Computer Vision. 2023.

**Comment by Duanener** [comment]
Thanks a lot for your help!

**Comment by CPFelix** [comment]
@qingshi9974  你好，针对real模式下压缩解压过慢问题，我根据其他压缩算法对模型进行了修改，但不确定是否存在问题，想请你帮忙看看。目前训练是正常收敛的，具体指标还没对比。
`# 改进版FTIC
class FrequencyAwareTransFormer(CompressionModel):
    def __init__(self, config=[2, 2, 2, 2, 2, 2], head_dim=[8, 16, 32, 32, 16, 8], drop_path_rate=0,
                 N=int(128 * width_ratio), M=int(320 * width_ratio), num_slices=5, max_support_slices=5, training=False, cca_training = False, **kwargs):
        super().__init__()
        self.training = training
        self.cca_training = cca_training
        self.config = config
        self.head_dim = head_dim
        self.window_size = 8
        self.num_slices = num_slices
        self.max_support_slices = max_support_slices
        self.tca_depth = int(12 * depth_ratio)
        self.tca_ratio = 4
        self.lower_bound = 0.01

        self.M = M
        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, sum(config))]
        N1 = int(96 * width_ratio)
        N2 = int(144 * width_ratio)
        N3 = int(256 * width_ratio)

        self.m_down1 = [FAT_Block(N1, self.head_dim[0], self.window_size, self.window_size * 2, dpr[i],
                                  'W' if not i % 2 else 'SW')
                        for i in range(config[0])] + \
                       [ResidualBlockWithStride(N1, N2, stride=2)]

        self.m_down2 = [FAT_Block(N2, self.head_dim[1], self.window_size, self.window_size * 2, dpr[i + 2],
                                  'W' if not i % 2 else 'SW')
                        for i in range(config[1])] + \
                       [ResidualBlockWithStride(N2, N3, stride=2)]

        self.m_down3 = [FAT_Block(N3, self.head_dim[2], self.window_size, self.window_size * 2, dpr[i + 4],
                                  'W' if not i % 2 else 'SW')
                        for i in range(config[2])] + \
                       [conv3x3(N3, M, stride=2)]

        dpr = dpr[::-1]
        self.m_up1 = [FAT_Block(N3, self.head_dim[3], self.window_size, self.window_size * 2, dpr[i],
                                'W' if not i % 2 else 'SW')
                      for i in range(config[3])] + \
                     [ResidualBlockUpsample(N3, N2, 2)]
        self.m_up2 = [FAT_Block(N2, self.head_dim[4], self.window_size, self.window_size * 2, dpr[i + 2],
                                'W' if not i % 2 else 'SW')
                      for i in range(config[4])] + \
                     [ResidualBlockUpsample(N2, N1, 2)]
        self.m_up3 = [FAT_Block(N1, self.head_dim[5], self.window_size, self.window_size * 2, dpr[i + 4],
                                'W' if not i % 2 else 'SW')
                      for i in range(config[5])] + \
                     [subpel_conv3x3(N1, 3, 2)]

        self.g_a = nn.Sequential(*[ResidualBlockWithStride(3, N1, 2)] + self.m_down1 + self.m_down2 + self.m_down3)
        self.g_s = nn.Sequential(*[ResidualBlockUpsample(M, N3, 2)] + self.m_up1 + self.m_up2 + self.m_up3)

        self.ha_down1 = [FAT_Block(N * 2, 32, 2, 4, 0, 'W' if not i % 2 else 'SW', True)
                         for i in range(config[0])] + \
                        [conv3x3(2 * N, 192, stride=2)]

        self.h_a = nn.Sequential(
            *[ResidualBlockWithStride(int(320 * width_ratio), N3, 2)] + \
             self.ha_down1
        )

        self.hs_up1 = [FAT_Block(N * 2, 32, 2, 4, 0, 'W' if not i % 2 else 'SW', True)
                       for i in range(config[3])] + \
                      [subpel_conv3x3(2 * N, int(320 * width_ratio), 2)]

        self.h_mean_s = nn.Sequential(
            *[ResidualBlockUpsample(192, 2 * N, 2)] + \
             self.hs_up1
        )

        self.hs_up2 = [FAT_Block(N * 2, 32, 2, 4, 0, 'W' if not i % 2 else 'SW', True)
                       for i in range(config[3])] + \
                      [subpel_conv3x3(2 * N, int(320 * width_ratio), 2)]

        self.h_scale_s = nn.Sequential(
            *[ResidualBlockUpsample(192, 2 * N, 2)] + \
             self.hs_up2
        )

        if cca_training:
            self.aux_entropymodel = AuxEntropyModel(M, [1, 1, 1, 1, 1], 224, 4)

        self.tca = TCA_EntropyModel(dim=M, ratio=self.tca_ratio, depth=self.tca_depth, slices=self.num_slices)
        self.entropy_bottleneck = EntropyBottleneck(192)
        self.gaussian_conditional = GaussianConditional(None)

    def forward(self, x):
        y = self.g_a(x)
        z = self.h_a(y)
        _, z_likelihoods = self.entropy_bottleneck(z)

        z_offset = self.entropy_bottleneck._get_medians()
        z_tmp = z - z_offset
        z_hat = ste_round(z_tmp) + z_offset

        scales_hyper = self.h_scale_s(z_hat)
        means_hyper = self.h_mean_s(z_hat)
        channel_per_slices = self.M // self.num_slices

        y_hat_coded = torch.zeros((z_hat.shape[0], self.M, z_hat.shape[2] * 4, z_hat.shape[3] * 4)).to(z_hat.device)
        y_likelihood = []
        for slice_index in range(self.num_slices):
            means, scales, lrps = self.tca(torch.cat((means_hyper, scales_hyper), dim=1), y_hat_coded)
            mu = means[:, slice_index * channel_per_slices:(slice_index + 1) * channel_per_slices]
            scale = scales[:, slice_index * channel_per_slices:(slice_index + 1) * channel_per_slices]
            lrp = lrps[:, slice_index * channel_per_slices:(slice_index + 1) * channel_per_slices]
            y_slice = y[:, slice_index * channel_per_slices:(slice_index + 1) * channel_per_slices]

            _, y_slice_likelihood = self.gaussian_conditional(y_slice, scale, mu)
            y_likelihood.append(y_slice_likelihood)

            y_hat_slice = ste_round(y_slice - mu) + mu
            lrp = 0.5 * torch.tanh(lrp)
            y_hat_slice += lrp
            y_hat_coded[:, slice_index * channel_per_slices:(slice_index + 1) * channel_per_slices] = y_hat_slice

        if self.cca_training:
            y_aux_likelihoods, y_cca_likelihoods = self.aux_entropymodel(y, scales_hyper, means_hyper)

        y_likelihoods = torch.cat(y_likelihood, dim=1)
        x_hat = self.g_s(y_hat_coded)

        return {
            "x_hat": x_hat,
            "likelihoods": {"y": y_likelihoods, "z": z_likelihoods},
            "aux_likelihoods": {"y_aux": y_aux_likelihoods, "y_cca": y_cca_likelihoods} if self.cca_training else None,
        }

    def update(self, scale_table=None, force=False):
        if scale_table is None:
            scale_table = get_scale_table()
        updated = self.gaussian_conditional.update_scale_table(scale_table, force=force)
        updated |= super().update(force=force)
        return updated

    def load_state_dict(self, state_dict, strict=False):
        if not self.training:
            update_registered_buffers(
                self.gaussian_conditional,
                "gaussian_conditional",
                ["_quantized_cdf", "_offset", "_cdf_length", "scale_table"],
                state_dict,
            )
        super().load_state_dict(state_dict, strict=strict)

    @classmethod
    def from_state_dict(cls, state_dict):
        """Return a new model instance from `state_dict`."""
        N = state_dict["g_a.0.weight"].size(0)
        M = state_dict["g_a.6.weight"].size(0)
        net = cls(N, M)
        net.load_state_dict(state_dict)
        return net

    def compress(self, x):

        y = self.g_a(x)
        z = self.h_a(y)
        z_strings = self.entropy_bottleneck.compress(z)
        z_hat = self.entropy_bottleneck.decompress(z_strings, z.size()[-2:])

        latent_scales = self.h_scale_s(z_hat)
        latent_means = self.h_mean_s(z_hat)
        hyper = torch.cat((latent_means, latent_scales), dim=1)
        channel_per_slices = self.M // self.num_slices

        y_hat_coded = torch.zeros((1, self.M, z_hat.shape[2] * 4, z_hat.shape[3] * 4)).to(z_hat.device)

        cdf = self.gaussian_conditional.quantized_cdf.tolist()
        cdf_lengths = self.gaussian_conditional.cdf_length.reshape(-1).int().tolist()
        offsets = self.gaussian_conditional.offset.reshape(-1).int().tolist()

        encoder = BufferedRansEncoder()
        symbols_list = []
        indexes_list = []
        y_strings = []

        for slice_index in range(self.num_slices):
            means, scales, lrps = self.tca(hyper, y_hat_coded)

            mu = means[:, slice_index * channel_per_slices:(slice_index + 1) * channel_per_slices]
            scale = scales[:, slice_index * channel_per_slices:(slice_index + 1) * channel_per_slices]
            lrp = lrps[:, slice_index * channel_per_slices:(slice_index + 1) * channel_per_slices]
            y_slice = y[:, slice_index * channel_per_slices:(slice_index + 1) * channel_per_slices]

            index = self.gaussian_conditional.build_indexes(scale)
            y_q_slice = self.gaussian_conditional.quantize(y_slice, "symbols", mu)
            y_hat_slice = y_q_slice + mu

            symbols_list.extend(y_q_slice.reshape(-1).tolist())
            indexes_list.extend(index.reshape(-1).tolist())

            lrp = 0.5 * torch.tanh(lrp)
            y_hat_slice += lrp
            y_hat_coded[:, slice_index * channel_per_slices:(slice_index + 1) * channel_per_slices] = y_hat_slice

        encoder.encode_with_indexes(symbols_list, indexes_list, cdf, cdf_lengths, offsets)
        y_string = encoder.flush()
        y_strings.append(y_string)

        return {"strings": [y_strings, z_strings], "shape": z.size()[-2:]}

    def _likelihood(self, inputs, scales, means=None):
        half = float(0.5)
        if means is not None:
            values = inputs - means
        else:
            values = inputs

        scales = torch.max(scales, torch.tensor(0.11))
        values = torch.abs(values)
        upper = self._standardized_cumulative((half - values) / scales)
        lower = self._standardized_cumulative((-half - values) / scales)
        likelihood = upper - lower
        return likelihood

    def _standardized_cumulative(self, inputs):
        half = float(0.5)
        const = float(-(2 ** -0.5))
        # Using the complementary error function maximizes numerical precision.
        return half * torch.erfc(const * inputs)

    def decompress(self, strings, z_shape):
        z_hat = self.entropy_bottleneck.decompress(strings[1], z_shape)
        latent_scales = self.h_scale_s(z_hat)
        latent_means = self.h_mean_s(z_hat)
        hyper = torch.cat((latent_means, latent_scales), dim=1)
        y_shape = [z_hat.shape[2] * 4, z_hat.shape[3] * 4]
        y_hat_coded = torch.zeros((1, self.M, z_hat.shape[2] * 4, z_hat.shape[3] * 4)).to(z_hat.device)
        lrp_coded = torch.zeros((1, self.M, z_hat.shape[2] * 4, z_hat.shape[3] * 4)).to(z_hat.device)
        channel_per_slices = self.M // self.num_slices

        y_string = strings[0][0]

        cdf = self.gaussian_conditional.quantized_cdf.tolist()
        cdf_lengths = self.gaussian_conditional.cdf_length.reshape(-1).int().tolist()
        offsets = self.gaussian_conditional.offset.reshape(-1).int().tolist()

        decoder = RansDecoder()
        decoder.set_stream(y_string)

        for slice_index in range(self.num_slices):
            means, scales, lrps = self.tca(hyper, y_hat_coded)
            mu = means[:, slice_index * channel_per_slices:(slice_index + 1) * channel_per_slices]
            scale = scales[:, slice_index * channel_per_slices:(slice_index + 1) * channel_per_slices]
            lrp = lrps[:, slice_index * channel_per_slices:(slice_index + 1) * channel_per_slices]

            index = self.gaussian_conditional.build_indexes(scale)

            rv = decoder.decode_stream(index.reshape(-1).tolist(), cdf, cdf_lengths, offsets)
            rv = torch.Tensor(rv).reshape(1, -1, y_shape[0], y_shape[1])
            y_hat_slice = self.gaussian_conditional.dequantize(rv, mu)

            lrp = 0.5 * torch.tanh(lrp)
            y_hat_slice += lrp

            y_hat_coded[:, slice_index * channel_per_slices:(slice_index + 1) * channel_per_slices] = y_hat_slice


        y_hat = y_hat_coded
        x_hat = self.g_s(y_hat).clamp_(0, 1)

        return {"x_hat": x_hat}`

**Comment by qingshi9974** [comment]
> [@qingshi9974](https://github.com/qingshi9974) 你好，针对real模式下压缩解压过慢问题，我根据其他压缩算法对模型进行了修改，但不确定是否存在问题，想请你帮忙看看。目前训练是正常收敛的，具体指标还没对比。 `
> 
> class FrequencyAwareTransFormer(CompressionModel):
> 
> ```
> def __init__(self, config=[2, 2, 2, 2, 2, 2], head_dim=[8, 16, 32, 32, 16, 8], drop_path_rate=0,N=int(128 * width_ratio),,M=int(320 * width_ratio), num_slices=5, max_support_slices=5, training=False, cca_training = False, **kwargs):
>     super().__init__()
>     self.training = training
>     self.cca_training = cca_training
>     self.config = config
>     self.head_dim = head_dim
>     self.window_size = 8
>     self.num_slices = num_slices
>     self.max_support_slices = max_support_slices
>     self.tca_depth = int(12 * depth_ratio)
>     self.tca_ratio = 4
>     self.lower_bound = 0.01
>     self.M = M
>     dpr = [x.item() for x in torch.linspace(0, drop_path_rate, sum(config))]
>     N1 = int(96 * width_ratio)
>     N2 = int(144 * width_ratio)
>     N3 = int(256 * width_ratio)
>     self.m_down1 = [FAT_Block(N1, self.head_dim[0], self.window_size, self.window_size * 2, dpr[i],
>                               'W' if not i % 2 else 'SW')
>                     for i in range(config[0])] + \
>                    [ResidualBlockWithStride(N1, N2, stride=2)]
> 
>     self.m_down2 = [FAT_Block(N2, self.head_dim[1], self.window_size, self.window_size * 2, dpr[i + 2],
>                               'W' if not i % 2 else 'SW')
>                     for i in range(config[1])] + \
>                    [ResidualBlockWithStride(N2, N3, stride=2)]
> 
>     self.m_down3 = [FAT_Block(N3, self.head_dim[2], self.window_size, self.window_size * 2, dpr[i + 4],
>                               'W' if not i % 2 else 'SW')
>                     for i in range(config[2])] + \
>                    [conv3x3(N3, M, stride=2)]
> 
>     dpr = dpr[::-1]
>     self.m_up1 = [FAT_Block(N3, self.head_dim[3], self.window_size, self.window_size * 2, dpr[i],
>                             'W' if not i % 2 else 'SW')
>                   for i in range(config[3])] + \
>                  [ResidualBlockUpsample(N3, N2, 2)]
>     self.m_up2 = [FAT_Block(N2, self.head_dim[4], self.window_size, self.window_size * 2, dpr[i + 2],
>                             'W' if not i % 2 else 'SW')
>                   for i in range(config[4])] + \
>                  [ResidualBlockUpsample(N2, N1, 2)]
>     self.m_up3 = [FAT_Block(N1, self.head_dim[5], self.window_size, self.window_size * 2, dpr[i + 4],
>                             'W' if not i % 2 else 'SW')
>                   for i in range(config[5])] + \
>                  [subpel_conv3x3(N1, 3, 2)]
> 
>     self.g_a = nn.Sequential(*[ResidualBlockWithStride(3, N1, 2)] + self.m_down1 + self.m_down2 + self.m_down3)
>     self.g_s = nn.Sequential(*[ResidualBlockUpsample(M, N3, 2)] + self.m_up1 + self.m_up2 + self.m_up3)
> 
>     self.ha_down1 = [FAT_Block(N * 2, 32, 2, 4, 0, 'W' if not i % 2 else 'SW', True)
>                      for i in range(config[0])] + \
>                     [conv3x3(2 * N, 192, stride=2)]
> 
>     self.h_a = nn.Sequential(
>         *[ResidualBlockWithStride(int(320 * width_ratio), N3, 2)] + \
>          self.ha_down1
>     )
> 
>     self.hs_up1 = [FAT_Block(N * 2, 32, 2, 4, 0, 'W' if not i % 2 else 'SW', True)
>                    for i in range(config[3])] + \
>                   [subpel_conv3x3(2 * N, int(320 * width_ratio), 2)]
> 
>     self.h_mean_s = nn.Sequential(
>         *[ResidualBlockUpsample(192, 2 * N, 2)] + \
>          self.hs_up1
>     )
> 
>     self.hs_up2 = [FAT_Block(N * 2, 32, 2, 4, 0, 'W' if not i % 2 else 'SW', True)
>                    for i in range(config[3])] + \
>                   [subpel_conv3x3(2 * N, int(320 * width_ratio), 2)]
> 
>     self.h_scale_s = nn.Sequential(
>         *[ResidualBlockUpsample(192, 2 * N, 2)] + \
>          self.hs_up2
>     )
> 
>     if cca_training:
>         self.aux_entropymodel = AuxEntropyModel(M, [1, 1, 1, 1, 1], 224, 4)
> 
>     self.tca = TCA_EntropyModel(dim=M, ratio=self.tca_ratio, depth=self.tca_depth, slices=self.num_slices)
>     self.entropy_bottleneck = EntropyBottleneck(192)
>     self.gaussian_conditional = GaussianConditional(None)
> 
> def forward(self, x):
>     y = self.g_a(x)
>     z = self.h_a(y)
>     _, z_likelihoods = self.entropy_bottleneck(z)
> 
>     z_offset = self.entropy_bottleneck._get_medians()
>     z_tmp = z - z_offset
>     z_hat = ste_round(z_tmp) + z_offset
> 
>     scales_hyper = self.h_scale_s(z_hat)
>     means_hyper = self.h_mean_s(z_hat)
>     channel_per_slices = self.M // self.num_slices
> 
>     y_hat_coded = torch.zeros((z_hat.shape[0], self.M, z_hat.shape[2] * 4, z_hat.shape[3] * 4)).to(z_hat.device)
>     y_likelihood = []
>     for slice_index in range(self.num_slices):
>         means, scales, lrps = self.tca(torch.cat((means_hyper, scales_hyper), dim=1), y_hat_coded)
>         mu = means[:, slice_index * channel_per_slices:(slice_index + 1) * channel_per_slices]
>         scale = scales[:, slice_index * channel_per_slices:(slice_index + 1) * channel_per_slices]
>         lrp = lrps[:, slice_index * channel_per_slices:(slice_index + 1) * channel_per_slices]
>         y_slice = y[:, slice_index * channel_per_slices:(slice_index + 1) * channel_per_slices]
> 
>         _, y_slice_likelihood = self.gaussian_conditional(y_slice, scale, mu)
>         y_likelihood.append(y_slice_likelihood)
> 
>         y_hat_slice = ste_round(y_slice - mu) + mu
>         lrp = 0.5 * torch.tanh(lrp)
>         y_hat_slice += lrp
>         y_hat_coded[:, slice_index * channel_per_slices:(slice_index + 1) * channel_per_slices] = y_hat_slice
> 
>     if self.cca_training:
>         y_aux_likelihoods, y_cca_likelihoods = self.aux_entropymodel(y, scales_hyper, means_hyper)
> 
>     y_likelihoods = torch.cat(y_likelihood, dim=1)
>     x_hat = self.g_s(y_hat_coded)
> 
>     return {
>         "x_hat": x_hat,
>         "likelihoods": {"y": y_likelihoods, "z": z_likelihoods},
>         "aux_likelihoods": {"y_aux": y_aux_likelihoods, "y_cca": y_cca_likelihoods} if self.cca_training else None,
>     }
> 
> def update(self, scale_table=None, force=False):
>     if scale_table is None:
>         scale_table = get_scale_table()
>     updated = self.gaussian_conditional.update_scale_table(scale_table, force=force)
>     updated |= super().update(force=force)
>     return updated
> 
> def load_state_dict(self, state_dict, strict=False):
>     if not self.training:
>         update_registered_buffers(
>             self.gaussian_conditional,
>             "gaussian_conditional",
>             ["_quantized_cdf", "_offset", "_cdf_length", "scale_table"],
>             state_dict,
>         )
>     super().load_state_dict(state_dict, strict=strict)
> 
> @classmethod
> def from_state_dict(cls, state_dict):
>     """Return a new model instance from `state_dict`."""
>     N = state_dict["g_a.0.weight"].size(0)
>     M = state_dict["g_a.6.weight"].size(0)
>     net = cls(N, M)
>     net.load_state_dict(state_dict)
>     return net
> 
> def compress(self, x):
> 
>     y = self.g_a(x)
>     z = self.h_a(y)
>     z_strings = self.entropy_bottleneck.compress(z)
>     z_hat = self.entropy_bottleneck.decompress(z_strings, z.size()[-2:])
> 
>     latent_scales = self.h_scale_s(z_hat)
>     latent_means = self.h_mean_s(z_hat)
>     hyper = torch.cat((latent_means, latent_scales), dim=1)
>     channel_per_slices = self.M // self.num_slices
> 
>     y_hat_coded = torch.zeros((1, self.M, z_hat.shape[2] * 4, z_hat.shape[3] * 4)).to(z_hat.device)
> 
>     cdf = self.gaussian_conditional.quantized_cdf.tolist()
>     cdf_lengths = self.gaussian_conditional.cdf_length.reshape(-1).int().tolist()
>     offsets = self.gaussian_conditional.offset.reshape(-1).int().tolist()
> 
>     encoder = BufferedRansEncoder()
>     symbols_list = []
>     indexes_list = []
>     y_strings = []
> 
>     for slice_index in range(self.num_slices):
>         means, scales, lrps = self.tca(hyper, y_hat_coded)
> 
>         mu = means[:, slice_index * channel_per_slices:(slice_index + 1) * channel_per_slices]
>         scale = scales[:, slice_index * channel_per_slices:(slice_index + 1) * channel_per_slices]
>         lrp = lrps[:, slice_index * channel_per_slices:(slice_index + 1) * channel_per_slices]
>         y_slice = y[:, slice_index * channel_per_slices:(slice_index + 1) * channel_per_slices]
> 
>         index = self.gaussian_conditional.build_indexes(scale)
>         y_q_slice = self.gaussian_conditional.quantize(y_slice, "symbols", mu)
>         y_hat_slice = y_q_slice + mu
> 
>         symbols_list.extend(y_q_slice.reshape(-1).tolist())
>         indexes_list.extend(index.reshape(-1).tolist())
> 
>         lrp = 0.5 * torch.tanh(lrp)
>         y_hat_slice += lrp
>         y_hat_coded[:, slice_index * channel_per_slices:(slice_index + 1) * channel_per_slices] = y_hat_slice
> 
>     encoder.encode_with_indexes(symbols_list, indexes_list, cdf, cdf_lengths, offsets)
>     y_string = encoder.flush()
>     y_strings.append(y_string)
> 
>     return {"strings": [y_strings, z_strings], "shape": z.size()[-2:]}
> 
> def _likelihood(self, inputs, scales, means=None):
>     half = float(0.5)
>     if means is not None:
>         values = inputs - means
>     else:
>         values = inputs
> 
>     scales = torch.max(scales, torch.tensor(0.11))
>     values = torch.abs(values)
>     upper = self._standardized_cumulative((half - values) / scales)
>     lower = self._standardized_cumulative((-half - values) / scales)
>     likelihood = upper - lower
>     return likelihood
> 
> def _standardized_cumulative(self, inputs):
>     half = float(0.5)
>     const = float(-(2 ** -0.5))
>     # Using the complementary error function maximizes numerical precision.
>     return half * torch.erfc(const * inputs)
> 
> def decompress(self, strings, z_shape):
>     z_hat = self.entropy_bottleneck.decompress(strings[1], z_shape)
>     latent_scales = self.h_scale_s(z_hat)
>     latent_means = self.h_mean_s(z_hat)
>     hyper = torch.cat((latent_means, latent_scales), dim=1)
>     y_shape = [z_hat.shape[2] * 4, z_hat.shape[3] * 4]
>     y_hat_coded = torch.zeros((1, self.M, z_hat.shape[2] * 4, z_hat.shape[3] * 4)).to(z_hat.device)
>     lrp_coded = torch.zeros((1, self.M, z_hat.shape[2] * 4, z_hat.shape[3] * 4)).to(z_hat.device)
>     channel_per_slices = self.M // self.num_slices
> 
>     y_string = strings[0][0]
> 
>     cdf = self.gaussian_conditional.quantized_cdf.tolist()
>     cdf_lengths = self.gaussian_conditional.cdf_length.reshape(-1).int().tolist()
>     offsets = self.gaussian_conditional.offset.reshape(-1).int().tolist()
> 
>     decoder = RansDecoder()
>     decoder.set_stream(y_string)
> 
>     for slice_index in range(self.num_slices):
>         means, scales, lrps = self.tca(hyper, y_hat_coded)
>         mu = means[:, slice_index * channel_per_slices:(slice_index + 1) * channel_per_slices]
>         scale = scales[:, slice_index * channel_per_slices:(slice_index + 1) * channel_per_slices]
>         lrp = lrps[:, slice_index * channel_per_slices:(slice_index + 1) * channel_per_slices]
> 
>         index = self.gaussian_conditional.build_indexes(scale)
> 
>         rv = decoder.decode_stream(index.reshape(-1).tolist(), cdf, cdf_lengths, offsets)
>         rv = torch.Tensor(rv).reshape(1, -1, y_shape[0], y_shape[1])
>         y_hat_slice = self.gaussian_conditional.dequantize(rv, mu)
> 
>         lrp = 0.5 * torch.tanh(lrp)
>         y_hat_slice += lrp
> 
>         y_hat_coded[:, slice_index * channel_per_slices:(slice_index + 1) * channel_per_slices] = y_hat_slice
> 
> 
>     y_hat = y_hat_coded
>     x_hat = self.g_s(y_hat).clamp_(0, 1)
> 
>     return {"x_hat": x_hat}
> ```
> 
> `

你好，此前我自己试过类似的训练方式，会出现熵模型训练不稳定的情况，如果训练稳定的话，应该是没有问题的。

**Comment by qingshi9974** [comment]
@CPFelix 此前我自己试过类似的训练方式，会出现熵模型训练不稳定的情况。

**Comment by qingshi9974** [comment]
@CPFelix 你好，此前我自己试过类似的训练方式，会出现熵模型训练不稳定的情况。如果训练稳定的话，应该是没有问题的。

**Comment by paomian001** [comment]
作者您好，请问您与其他方法做RD曲线对比时，曲线上的6个点是否是λ分别为0.0025, 0.0035, 0.0067, 0.0130, 0.0250, 0.0483时候对应的psnr及bpp

**Comment by paomian001** [comment]
> 作者您好，请问您与其他方法做RD曲线对比时，曲线上的6个点是否是λ分别为0.0025, 0.0035, 0.0067, 0.0130, 0.0250, 0.0483时候对应的psnr及bpp

@qingshi9974
